src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Source_Names__c</fullName>
        <inlineHelpText>A list of report and campaign sources that referenced this Contact or Lead in the Campaign&apos;s List.</inlineHelpText>
        <label>Source Names</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Root_Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sources__c</fullName>
        <label>Sources</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CampaignListToCampaignMemberBatch.cls
public class CampaignListToCampaignMemberBatch extends BatchableSequence implements Database.Batchable<sObject> {
    private Id campaignId;
    private Id segmentId;
    private CampaignListCriteria listCriteria;

    public CampaignListToCampaignMemberBatch(Id campaignId, Id segmentId, CampaignListCriteria listCriteria) {
        this.campaignId = campaignId;
        this.segmentId = segmentId;
        this.listCriteria = listCriteria;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Contact__c, Lead__c, Sources__c, Source_Names__c FROM Member__c WHERE Root_Segment__c = :segmentId'
        );
    }

    public void execute(Database.BatchableContext bc, List<Member__c> scope) {
        List<CampaignMember> campaignMembers = new List<CampaignMember>();

        for (Member__c m : scope) {
            CampaignListMember member = new CampaignListMember(m);
            if (listCriteria.meetsCriteria(member)) {
                CampaignMember cm = member.getCampaignMember();
                cm.CampaignId = campaignId;
                campaignMembers.add(cm);
            }
        }

        insert campaignMembers;
        delete scope;
    }

    public override void execute() {
        Database.executeBatch(this, getScope());
    }
}