src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <picklist>
            <picklistValues>
                <fullName>AND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Root_Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Root Segments</relationshipLabel>
        <relationshipName>RootSegments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>SEG-{000000}</displayFormat>
        <label>Segment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SegmentMapper_TEST.cls
@isTest
private class SegmentMapper_TEST {
    
    @isTest static void test_method_one() {
        integer numChildren = 3;

        Segment__c rootSegment = new Segment__c(Operation__c=Label.logicAND);
        insert rootSegment;
        
        list<Segment__c> childSegments = new list<Segment__c>();
        for (integer i=0;i<numChildren;i++) {
            childSegments.add(new Segment__c(
                Operation__c = Label.logicOR,
                Root_Segment__c = rootSegment.id,
                Parent_Segment__c = rootSegment.id
            ));
        }
        insert childSegments;

        Segment__c grandchildSegment = new Segment__c(
            Operation__c = Label.logicOR,
            Root_Segment__c = rootSegment.id,
            Parent_Segment__c = childSegments[0].id
        );
        insert grandchildSegment;
        
        CSegment mappedRoot = SegmentMapper.mapRootSegment(rootSegment);

        system.assertEquals(3,mappedRoot.listChildCSegments.size(),'The root segment should have three child segments.');
        Segment__c testGrandchildSegment;
        for (CSegment cs : mappedRoot.listChildCSegments) {
            if (cs.listChildCSegments.size() > 0) {
                testGrandchildSegment = cs.listChildCSegments.get(0).Segment;
            }
        }
        system.assertNotEquals(null,testGrandchildSegment,'The grandchild should exist.');
        system.assertEquals(grandchildSegment.id, testGrandchildSegment.id, 'The correct grandchild should be found.');
    }
}